version: "3.9"

services:

  app:
    build: ./app
    container_name: final-project-app
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    depends_on:
      - db
    volumes:
      - ./app:/app
      - /app/node_modules

  db:
    image: mysql:8
    container_name: final-project-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: