version: '3.8'

services:
  # Service untuk Aplikasi Node.js
  app-service:
    build:
      context: ./app            
      dockerfile: Dockerfile
    container_name: challenge-node-app
    ports:
      - "${PORT}:${PORT}"       
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - pnb-network
    depends_on:
      db-container:
        condition: service_healthy # <--- MEMAKSA BACKEND MENUNGGU SAMPAI DATABASE SEHAT

  # Service untuk Database MySQL
  db-container:
    image: mysql:8
    container_name: challenge-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}         
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pnb-network
    # --- TAMBAHKAN BLOK HEALTHCHECK INI ---
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  pnb-network:
    driver: bridge